apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign-analytics-api
  labels:
    app: campaign-analytics
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: campaign-analytics
      component: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: campaign-analytics
        component: api
    spec:
      containers:
      - name: api
        image: ${REGISTRY_URL}/campaign-analytics-api:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: CA_POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: campaign-analytics-config
              key: postgres-host
        - name: CA_POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: campaign-analytics-config
              key: postgres-port
        - name: CA_POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: campaign-analytics-config
              key: postgres-database
        - name: CA_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: campaign-analytics-secrets
              key: postgres-username
        - name: CA_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: campaign-analytics-secrets
              key: postgres-password
        - name: CA_CLICKHOUSE_HOST
          valueFrom:
            configMapKeyRef:
              name: campaign-analytics-config
              key: clickhouse-host
        - name: CA_CLICKHOUSE_PORT
          valueFrom:
            configMapKeyRef:
              name: campaign-analytics-config
              key: clickhouse-port
        - name: CA_CLICKHOUSE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: campaign-analytics-config
              key: clickhouse-database
        - name: CA_CLICKHOUSE_USERNAME
          valueFrom:
            secretKeyRef:
              name: campaign-analytics-secrets
              key: clickhouse-username
        - name: CA_CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: campaign-analytics-secrets
              key: clickhouse-password
        - name: CA_REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: campaign-analytics-config
              key: redis-addr
        - name: CA_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: campaign-analytics-secrets
              key: redis-password
        - name: CA_KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: campaign-analytics-config
              key: kafka-brokers
        - name: CA_JWT_KEY
          valueFrom:
            secretKeyRef:
              name: campaign-analytics-secrets
              key: jwt-key
      imagePullSecrets:
      - name: registry-credentials