apiVersion: v1
kind: Service
metadata:
  name: campaign-analytics-api
  labels:
    app: campaign-analytics
    component: api
spec:
  selector:
    app: campaign-analytics
    component: api
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: campaign-analytics-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  rules:
  - host: api.analytics.zocket.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: campaign-analytics-api
            port:
              number: 80
  tls:
  - hosts:
    - api.analytics.zocket.com
    secretName: campaign-analytics-tls
